### ISSUE TITLE
Utilização

### ISSUE THREAD

**Issue by arquitetoitamar** [rterrabh/archci#1]
está funcionando o Archci???

gostaria de fazer uns testes aqui na empresa

**Comment by rterrabh** [comment]
Olá Itamar, boa tarde. Sim está funcionando. Peço que entre em contato comigo pelo "terra@dcc.ufla.br" que posso te explicar melhor, inclusive disponibilizando materiais de instalação. Att.,
--
R. Terra
Professor, DCC, UFLA
